### ISSUE TITLE
Freezes on exit raspberry pi

### ISSUE THREAD

**Issue by HerbFargus** [libretro/libretro-wolfenstein3d#1]
It compiles, loads, and plays just fine but when I exit it freezes as it seems to be leaving the framebuffer in an unusable state. 

I'm on a raspberry pi 3 using RetroPie (Raspbian Jessie)

Let me know if there are any log files or any more info that you would need.

**Comment by twinaphex** [comment]
This doesn't even work yet, so there is no point yet pointing issues out. The libretro port has also yet to be done.

**Comment by HerbFargus** [comment]
Apologies for the noise, keep up the good work
